### ISSUE TITLE
Angular-cli?

### ISSUE THREAD

**Issue by ccpony** [creativetimofficial/material-dashboard-angular#1]
Great template!  How about an angular-cli/Webpack version?

**Comment by alexandru-paduraru** [comment]
@ccpony thank you for the kind words! At this moment we are working on Material Dashboard PRO Angular 2, then we will implement the Angular-CLI version of our products. Stay tuned, it will come soon. BTW, if you have knowledge of Angular-CLI and want to contribute we would be glad to add you as a collaborator.

Best,
Alex

Managing Partner at www.creative-tim.com

**Comment by ccpony** [comment]
I’m afraid that I’m too booked to contribute at this time, but I will be the first in line to purchased your PRO ng2-material template.  I’m sure that it will be the best one out there.  Any ETA?

**Comment by alexandru-paduraru** [comment]
@ccpony it should be published this week. Don't know exactly the day, it's a surprise :-))

**Comment by sdey0081** [comment]
hi @alexandru-paduraru you have done amazing job and also amazing template.
I already completed several projects using this template based on angular-cli.
If possible, I am also available to contribute for angular-cli version.

**Comment by alexandru-paduraru** [comment]
@sdey0081 thank you mate! Glad that you like it and happy to know that it was useful. That would be great. Please let us know which is the best option to achieve this, what we need to prepare on our side for you?

Best,
Alex

**Comment by sdey0081** [comment]
Don't need anything.
Do you need to work on your repository or should I create on mine?
Anything is welcome, and once done, I will commit the basic project. :)

Thank you

**Comment by alexandru-paduraru** [comment]
@sdey0081 I think the best way is to fork the current project, in this way you will be the owner and then we will add links from our repo and site to your repo and vice-versa. We will filter then the devs who want the regular Angular2 version or those who want the AngularCLI version. From what I know the webpack is handling a little bit different the structure of the files and dependencies. I'm I right?

**Comment by sdey0081** [comment]
ok

**Comment by ccpony** [comment]
Status on your Material Dashboard Pro Angular 2 - - angular-cli version?

**Comment by alexandru-paduraru** [comment]
@ccpony the PRO version was just released: http://md-pro-angular2.creative-tim.com/#/dashboard for the CLI version we don't have an ETA yet :-(

**Comment by alexandru-paduraru** [comment]
@ccpony if you want to get the PRO version, please let me know and you will get 30% discount for being a user of the Free version :D

**Comment by ccpony** [comment]
Thank you Alex!  But I need to wait for the CLI version.  As soon as that’s available, I’ll purchase your product.

Jeff

**Comment by sdey0081** [comment]
Hi buddies, 
I had so busy days and couldn't work with... 
Today, I just pushed angular-cli version here: https://github.com/tiniestory/ng-admin.
Feel free to ask if you have any questions. Warmest regards!

**Comment by alexandru-paduraru** [comment]
@sdey0081 wow! that's awesome. I will check it with @chelaruc and if everything is fine on it we will link from this repo and from our website to it. Hope this is ok with you.

Best,
Alex

**Comment by jackrvaughan** [comment]
Were there any issues? Does the pro version have the cli now?

**Comment by Gironda** [comment]
Hello Alex, can you give us a estimated date for the CLI version?

**Comment by alexandru-paduraru** [comment]
@jackrvaughan @Gironda thank the PRO version CLI will come on 15th May, stay tuned, it will be way better than the current plain Angular 2. 

Best,
Alex
