### ISSUE TITLE
install node modules don't work

### ISSUE THREAD

**Issue by enzinoieva** [creativetimofficial/material-dashboard-angular#10]
Hello,
I tried to install : "npm install ng2-datepicker --save" .
I followed the procedure but the component does not work.
The error returned by the chrome console is:

localhost:3000/ng2-datepicker Failed to load resource: the server responded with a status of 404 (Not Found).

Thank you so mutch!

**Comment by alexandru-paduraru** [comment]
@enzinoieva thank you for using our product. It seems the problem is from Datepicker, not from our Material Dashboard. I've found this on StackOverflow, hope it will help you: http://stackoverflow.com/questions/40289639/ng2-datepicker-404-not-found-latest-rc

Best,
Alex
