### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by mrbormeth** [creativetimofficial/material-dashboard-angular#12]
Hello :) 

Love the template, looks awesome!!

Does it work with angular 4 or do you maybe know where to start to convert it?

**Comment by alexandru-paduraru** [comment]
@mrbormeth thank you for the kind words. We have in plan to upgrade it to Angular 4 as soon as we finish with the development of MD Pro Angular CLI. If you want to contribute just make a pull request, the product is under MIT license, so we need the help of the community to support it.

Best,
Alex
