### ISSUE TITLE
Floating Label is broken with default value

### ISSUE THREAD

**Issue by gogo217** [creativetimofficial/material-dashboard-angular#15]
![image](https://user-images.githubusercontent.com/20570634/27579207-5c6815b0-5b59-11e7-8a4b-28eb47547d59.png)

```
<div class="form-group label-floating">
        <label class="control-label">Description</label>
        <input type="text" class="form-control" [value]="item.description">
</div>
```
This issue occurs when I use angular 4 binding. 
Thanks

**Comment by alexandru-paduraru** [comment]
@gogo217 thank you for using our product. Please check the solution that we have here: https://github.com/creativetimofficial/material-dashboard-pro/issues/50 Basically you need to manually remove the is-empty class from the parent of the input. We will have a fix for this soon.

Best,
Alex

**Comment by gogo217** [comment]
Thanks, but below code snippet would also be helpful.
```
$.material.options.autofill = true;
$.material.init();
```

**Comment by aomegax** [comment]
Hi, @gogo217. Your workaround works only if there is only one input or textbox. If there are multiple fields it is applied only to the first.
