### ISSUE TITLE
Jquery fails when lazy loading

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/material-dashboard-angular#16]
Is there a way to get the jquery styling to load along with the module when lazyloading? I have all the scripts listed in the .angular-cli.json file but they don't load along with the module.

**Comment by alexandru-paduraru** [comment]
@elvnthaus can you please let us know specifically what you want to achieve? Did you try to add your methods inside $(document).ready(function(){...//here })? That will make sure the jQuery is loaded when you execute what is inside. 

Best, Alex!
