### ISSUE TITLE
(ng2) npm start

### ISSUE THREAD

**Issue by xSirk** [creativetimofficial/material-dashboard-angular#17]
I'm getting this error. I'm really new to Angular. Help pls.
![mintty_2017-07-04_17-39-18](https://user-images.githubusercontent.com/16200935/27843241-9c2dc8b2-60df-11e7-8807-8f2521b14ebb.png)

**Comment by alexandru-paduraru** [comment]
@xSirk thank you for using our product. Do you use the PRO or the Free? This is the repo for the free. Also please make sure you downloaded the latest v1.2.1 version of the PRO and let us know your status.

Best,
Alex
