### ISSUE TITLE
Bootstrap Modal apprears behind the backdrop

### ISSUE THREAD

**Issue by wadel86** [creativetimofficial/material-dashboard-angular#2]
I'm trying to add the ng2-bootstrap modal with the template but the modal appears behind the backdrop, 

I added $('.modal').appendTo("body"); inside the $(document).ready function but it didn't help.

**Comment by joanteixi** [comment]
I have same problem. the modal is opened but it's blocked, not possible to interact with it.

thks

**Comment by sdey0081** [comment]
Hi guys, it's so easy in angular 2 or higher.

Add this in the **component.ts**, 

`encapsulation: ViewEncapsulation.None`

And add the following style in the **component.css**,
```
.modal-backdrop {
    z-index: -1;
}
```

I checked this in angular 4 project, it worked.

Good luck :)

**Comment by joanteixi** [comment]
yeah! perfect! I changed the z-index but forgot totally about the existence of the encapsulation property. 

thks

**Comment by alexandru-paduraru** [comment]
Hi guys, this is a bug from our product. I recommend you to delete the translate from the `.main-panel`, line 4837 and 648 in material-dashboard.css or if you want to use SASS inside sass/md/_responsive.scss line 137 and sass/md/_sidebar-and-main-panel.scss line 273

-webkit-transform: translate3d(0px, 0, 0);
    -moz-transform: translate3d(0px, 0, 0);
    -o-transform: translate3d(0px, 0, 0);
    -ms-transform: translate3d(0px, 0, 0);
    transform: translate3d(0px, 0, 0);

<img width="436" alt="screen shot 2017-06-13 at 18 23 25" src="https://user-images.githubusercontent.com/2517758/27090310-82cdaef8-5065-11e7-84a8-705dc10971fd.png">

Then everything will work fine without any additional changes from Angular.

**Comment by behimar** [comment]
nopee

**Comment by chelaruc** [comment]
@behimar what happened?
