### ISSUE TITLE
Lazy Loading or Routing problem

### ISSUE THREAD

**Issue by ZikZakJainy** [creativetimofficial/material-dashboard-angular#20]
I am using material-dashboard-angular version and using lazy loading but after loading 3-4 route it's not working, router navigate to particular component but template of component not load, and there is no error in console.
screenshot of my app.routing.ts and issue screen listed.
![screenshot 36](https://user-images.githubusercontent.com/24683659/29567696-9e1fd7fc-876b-11e7-89e1-865dc71890ac.png)
![screenshot 35](https://user-images.githubusercontent.com/24683659/29567697-9e248356-876b-11e7-8d60-e20869da8486.png)
you can check also in https://moneysave-fabea.firebaseapp.com/

**Comment by alexandru-paduraru** [comment]
@ZikZakJainy thank you for letting us know. Are you using the latest v1.4.0 version from our website? The one with CLI structure? Also, let us know where you have the repo so we can check the code.

I added my colleague Ciprian and he will have a look after you give us more details.
Best,
Alex
