### ISSUE TITLE
Example input labels do not float

### ISSUE THREAD

**Issue by drdreo** [creativetimofficial/material-dashboard-angular#21]
In the Example Page "User Profile" if you enter some text into the inputs, the label does not float upwards. 
The class "is-empty" needs to be removed accordingly.

**Comment by maximeburri** [comment]
It seems to come from a more general problem. From https://github.com/creativetimofficial/material-dashboard-angular/commit/22b2e086a965558336a09ac97377272245b5d91b : 
- Label of inputs does not float upwards
- Checkbox is not displayed 
- Tabs or button animation (the "round") doesn't works 

Old version (https://github.com/creativetimofficial/material-dashboard-angular/commit/22b2e086a965558336a09ac97377272245b5d91b) :+1: 
![works](https://user-images.githubusercontent.com/5551924/30545674-9e5e599e-9c8a-11e7-85cb-b8a7de474390.gif)
New version :
![doesnt-works](https://user-images.githubusercontent.com/5551924/30545678-a3a28498-9c8a-11e7-8f63-da9adcb24630.gif)

No error in ```ng serve``` or web console.

**Comment by chelaruc** [comment]
This is fixed
