### ISSUE TITLE
Button animations

### ISSUE THREAD

**Issue by hypertenso** [creativetimofficial/material-dashboard-angular#27]
Hello guys!

I have a problem with button animation. Some time ago I downloaded the Dashboard Angular 2+ (free version), installed the dependencies and then almost everything worked according to the online demo. I say "almost" becouse the button animation doesn't work properly. 

When I drag the mouse over the button, the float animation happens, but when I click on it, the click animation does not appear. It seems that the click didn't happen. 

Anyone know if this problem is already known? What information can I provide so that someone can help me?

Online demo: 
![online demo](https://user-images.githubusercontent.com/32783511/34569382-c1fa01d6-f14f-11e7-82c5-9fb6d5ed14ed.gif)

Local:
![local demo](https://user-images.githubusercontent.com/32783511/34569395-c8148b72-f14f-11e7-93bd-2c4e52eba8d2.gif)

**Comment by chelaruc** [comment]
Hi @hypertenso! Thank you for using our product! I have tested on our project and it is working good. Can you verify if you have these scripts inside `angular-cli.json`?
````
"../node_modules/bootstrap/dist/js/bootstrap.js",
 "../node_modules/bootstrap-material-design/dist/js/ripples.min.js",
 "../node_modules/bootstrap-material-design/dist/js/material.min.js",
````

Best, Ciprian

**Comment by hypertenso** [comment]
Hey @chelaruc, thank you so much. It was missing the `ripples.min.js` for some reason, weird. Anyway, solved my problem!
