### ISSUE TITLE
wizard multi form validation

### ISSUE THREAD

**Issue by seqato** [creativetimofficial/material-dashboard-angular#32]
how to do validation in the second step of wizard?

**Comment by chelaruc** [comment]
@seqato Do you have the pro version of this product? Please tell me the order details.

Best,
Ciprian

**Comment by seqato** [comment]
Hi.. Didn't get your question...

I  had purchased a discounted full bundle last year.

Is that what you are asking?

**Comment by chelaruc** [comment]
@seqato I'm asking if you have Material Dashboard Pro Angular, because here are the issues for the free version and this product doesn't have wizard.

**Comment by seqato** [comment]
Oh OK..

Yes i had purchased the material  dashboard pro angular product.




On 09-Mar-2018 2:21 PM, "Chelaru Ciprian" <notifications@github.com> wrote:

@seqato <https://github.com/seqato> I'm asking if you have Material
Dashboard Pro Angular, because here are the issues for the free version and
this product doesn't have wizard.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/creativetimofficial/material-dashboard-angular/issues/32#issuecomment-371751300>,
or mute the thread
