### ISSUE TITLE
ng build --aot=true

### ISSUE THREAD

**Issue by vignesh007vicky** [creativetimofficial/material-dashboard-angular#34]
HI ,

Thanks for this wonderfull theme.

i had a issue while bilding with aot

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/var/www/html/APPH/material-dashboard-angular/src'
#  ./src/main.ts 4:0-74
  multi ./src/main.ts

---------------------------------------------
angular/cli: 1.0.0
node: 8.9.4
os: linux x64
angular/common: 4.4.6
angular/compiler: 4.4.6
angular/core: 4.4.6
angular/forms: 4.4.6
angular/http: 4.4.6
angular/platform-browser: 4.4.6
angular/platform-browser-dynamic: 4.4.6
angular/router: 4.4.6

angular/cli: 1.0.0
angular/compiler-cli: 4.4.6
node -v
v8.9.4
npm -v
5.8.0
ubuntu 64bit os

Thanks
Vignesh

**Comment by chelaruc** [comment]
Hi, @vignesh007vicky. You need to update the dependencies for angular and @angular/cli.

Best,
Ciprian
