### ISSUE TITLE
PeerDependencies

### ISSUE THREAD

**Issue by KjetilHaaheim** [creativetimofficial/material-dashboard-angular#9]
Hi guys!

I am trying to run npm install, but I am encountering following issue:

> npm WARN angular-in-memory-web-api@0.1.17 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN angular-in-memory-web-api@0.1.17 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN ng2-bootstrap@1.1.17 requires a peer of @angular/common@^2.4.0 but none was installed.
npm WARN ng2-bootstrap@1.1.17 requires a peer of @angular/compiler@^2.4.0 but none was installed.
npm WARN ng2-bootstrap@1.1.17 requires a peer of @angular/core@^2.4.0 but none was installed.
npm WARN ng2-bootstrap@1.1.17 requires a peer of @angular/forms@^2.4.0 but none was installed.
npm WARN The package @types/core-js is included as both a dev and production dependency.

My npm-version is 4.4.4, and my Node version is 6.9.1. 

I have tried different ways of solving the problem, installing deps manually and running npm-install-peers, but I cannot get it to work. 

I am considering the Pro version, but I want to be certain I can get this running first. Any help would be greatly appreciated.

**Comment by chelaruc** [comment]
@KjetilHaaheim Thank you for your interest in our product. To get rid of warnings, you must change the dependencies from the package.json like that:
```
    "dependencies": {
        "@angular/common": "~2.4.9",
        "@angular/compiler": "~2.4.9",
        "@angular/core": "~2.4.9",
        "@angular/forms": "~2.4.9",
        "@angular/http": "~2.4.9",
        "@angular/platform-browser": "~2.4.9",
        "@angular/platform-browser-dynamic": "~2.4.9",
        "@angular/router": "~3.4.9",
        "@angular/upgrade": "~2.4.9",
        "@types/core-js": "0.9.35",
        "angular-in-memory-web-api": "0.3.1",
        "ng-chartist": "1.1.0",
        "angular2-google-maps": "~0.17.0",
        "chartist": "~0.9.8",
        "core-js": "~2.4.1",
        "jquery": "~3.1.1",
        "reflect-metadata": "~0.1.8",
        "rxjs": "5.0.1",
        "systemjs": "~0.19.41",
        "zone.js": "^0.7.2"
  }
```

Keep in touch,
Ciprian
